-- MySQL Script generated by MySQL Workbench
-- Tue Jun 23 17:48:36 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Marca` (
  `idMarca` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Status` INT NULL,
  PRIMARY KEY (`idMarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Modelo` (
  `idModelo` INT NOT NULL,
  `Nombre` VARCHAR(70) NULL,
  `Tipo_Motor` VARCHAR(45) NULL,
  `Transmision` VARCHAR(45) NULL,
  `Marca_idMarca` INT NOT NULL,
  PRIMARY KEY (`idModelo`),
  INDEX `fk_Modelo_Marca_idx` (`Marca_idMarca` ASC) VISIBLE,
  UNIQUE INDEX `Transmision_UNIQUE` (`Transmision` ASC) VISIBLE,
  CONSTRAINT `fk_Modelo_Marca`
    FOREIGN KEY (`Marca_idMarca`)
    REFERENCES `mydb`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Planta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Planta` (
  `idPlanta` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Tipo_Planta` VARCHAR(45) NULL,
  `Direccion` VARCHAR(100) NULL,
  PRIMARY KEY (`idPlanta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vehiculo` (
  `VIN` INT NOT NULL,
  `Precio` INT NULL,
  `Status` INT NULL,
  `Modelo_idModelo` INT NOT NULL,
  `Planta_idPlanta` INT NOT NULL,
  PRIMARY KEY (`VIN`),
  INDEX `fk_Vehiculo_Modelo1_idx` (`Modelo_idModelo` ASC) VISIBLE,
  INDEX `fk_Vehiculo_Planta1_idx` (`Planta_idPlanta` ASC) VISIBLE,
  CONSTRAINT `fk_Vehiculo_Modelo1`
    FOREIGN KEY (`Modelo_idModelo`)
    REFERENCES `mydb`.`Modelo` (`idModelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehiculo_Planta1`
    FOREIGN KEY (`Planta_idPlanta`)
    REFERENCES `mydb`.`Planta` (`idPlanta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedor` (
  `idProveedor` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Contacto` VARCHAR(100) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Correo` VARCHAR(45) NULL,
  `Status` VARCHAR(45) NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pieza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pieza` (
  `idPieza` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idPieza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proveedor_has_Pieza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedor_has_Pieza` (
  `Proveedor_idProveedor` INT NOT NULL,
  `Pieza_idPieza` INT NOT NULL,
  INDEX `fk_Proveedor_has_Pieza_Pieza1_idx` (`Pieza_idPieza` ASC) VISIBLE,
  INDEX `fk_Proveedor_has_Pieza_Proveedor1_idx` (`Proveedor_idProveedor` ASC) VISIBLE,
  CONSTRAINT `fk_Proveedor_has_Pieza_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `mydb`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proveedor_has_Pieza_Pieza1`
    FOREIGN KEY (`Pieza_idPieza`)
    REFERENCES `mydb`.`Pieza` (`idPieza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pieza_has_Modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pieza_has_Modelo` (
  `Pieza_idPieza` INT NOT NULL,
  `Modelo_idModelo` INT NOT NULL,
  INDEX `fk_Pieza_has_Modelo_Modelo1_idx` (`Modelo_idModelo` ASC) VISIBLE,
  INDEX `fk_Pieza_has_Modelo_Pieza1_idx` (`Pieza_idPieza` ASC) VISIBLE,
  CONSTRAINT `fk_Pieza_has_Modelo_Pieza1`
    FOREIGN KEY (`Pieza_idPieza`)
    REFERENCES `mydb`.`Pieza` (`idPieza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pieza_has_Modelo_Modelo1`
    FOREIGN KEY (`Modelo_idModelo`)
    REFERENCES `mydb`.`Modelo` (`idModelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Parte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Parte` (
  `idParte` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Planta_idPlanta` INT NOT NULL,
  `Modelo_idModelo` INT NOT NULL,
  PRIMARY KEY (`idParte`),
  INDEX `fk_Parte_Planta1_idx` (`Planta_idPlanta` ASC) VISIBLE,
  INDEX `fk_Parte_Modelo1_idx` (`Modelo_idModelo` ASC) VISIBLE,
  CONSTRAINT `fk_Parte_Planta1`
    FOREIGN KEY (`Planta_idPlanta`)
    REFERENCES `mydb`.`Planta` (`idPlanta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Parte_Modelo1`
    FOREIGN KEY (`Modelo_idModelo`)
    REFERENCES `mydb`.`Modelo` (`idModelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Concesionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Concesionario` (
  `idConcesionario` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Status` VARCHAR(1) NULL,
  `Concesionariocol` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`idConcesionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Concesionario_has_Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Concesionario_has_Marca` (
  `Concesionario_idConcesionario` INT NOT NULL,
  `Marca_idMarca` INT NOT NULL,
  INDEX `fk_Concesionario_has_Marca_Marca1_idx` (`Marca_idMarca` ASC) VISIBLE,
  INDEX `fk_Concesionario_has_Marca_Concesionario1_idx` (`Concesionario_idConcesionario` ASC) VISIBLE,
  CONSTRAINT `fk_Concesionario_has_Marca_Concesionario1`
    FOREIGN KEY (`Concesionario_idConcesionario`)
    REFERENCES `mydb`.`Concesionario` (`idConcesionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Concesionario_has_Marca_Marca1`
    FOREIGN KEY (`Marca_idMarca`)
    REFERENCES `mydb`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventario_Concesionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventario_Concesionario` (
  `idInventario_Concesionario` INT NOT NULL,
  `Status` VARCHAR(1) NULL,
  `Concesionario_idConcesionario` INT NOT NULL,
  `Vehiculo_VIN` INT NOT NULL,
  PRIMARY KEY (`idInventario_Concesionario`),
  INDEX `fk_Inventario_Concesionario_Concesionario1_idx` (`Concesionario_idConcesionario` ASC) VISIBLE,
  INDEX `fk_Inventario_Concesionario_Vehiculo1_idx` (`Vehiculo_VIN` ASC) VISIBLE,
  CONSTRAINT `fk_Inventario_Concesionario_Concesionario1`
    FOREIGN KEY (`Concesionario_idConcesionario`)
    REFERENCES `mydb`.`Concesionario` (`idConcesionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario_Concesionario_Vehiculo1`
    FOREIGN KEY (`Vehiculo_VIN`)
    REFERENCES `mydb`.`Vehiculo` (`VIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carroceria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carroceria` (
  `idCarroceria` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Modelo_idModelo` INT NOT NULL,
  PRIMARY KEY (`idCarroceria`),
  INDEX `fk_Carroceria_Modelo1_idx` (`Modelo_idModelo` ASC) VISIBLE,
  CONSTRAINT `fk_Carroceria_Modelo1`
    FOREIGN KEY (`Modelo_idModelo`)
    REFERENCES `mydb`.`Modelo` (`idModelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `idClientes` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Concesionario_idConcesionario` INT NOT NULL,
  PRIMARY KEY (`idClientes`),
  INDEX `fk_Clientes_Concesionario1_idx` (`Concesionario_idConcesionario` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_Concesionario1`
    FOREIGN KEY (`Concesionario_idConcesionario`)
    REFERENCES `mydb`.`Concesionario` (`idConcesionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Factura_Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Factura_Clientes` (
  `idFactura_Clientes` INT NOT NULL,
  `Fecha` DATE NULL,
  `Total` VARCHAR(45) NULL,
  `Impuesto` VARCHAR(45) NULL,
  `SubTotal` VARCHAR(45) NULL,
  `Concesionario_idConcesionario` INT NOT NULL,
  `Clientes_idClientes` INT NOT NULL,
  PRIMARY KEY (`idFactura_Clientes`),
  INDEX `fk_Factura_Clientes_Concesionario1_idx` (`Concesionario_idConcesionario` ASC) VISIBLE,
  INDEX `fk_Factura_Clientes_Clientes1_idx` (`Clientes_idClientes` ASC) VISIBLE,
  CONSTRAINT `fk_Factura_Clientes_Concesionario1`
    FOREIGN KEY (`Concesionario_idConcesionario`)
    REFERENCES `mydb`.`Concesionario` (`idConcesionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Clientes_Clientes1`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `mydb`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Detalle_Factura_Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Detalle_Factura_Clientes` (
  `Precio` INT NOT NULL,
  `Factura_Clientes_idFactura_Clientes` INT NOT NULL,
  `Inventario_Concesionario_idInventario_Concesionario` INT NOT NULL,
  INDEX `fk_Detalle_Factura_Clientes_Factura_Clientes1_idx` (`Factura_Clientes_idFactura_Clientes` ASC) VISIBLE,
  CONSTRAINT `fk_Detalle_Factura_Clientes_Factura_Clientes1`
    FOREIGN KEY (`Factura_Clientes_idFactura_Clientes`)
    REFERENCES `mydb`.`Factura_Clientes` (`idFactura_Clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_Factura_Clientes_Inventario_Concesionario1`
    FOREIGN KEY (`Inventario_Concesionario_idInventario_Concesionario`)
    REFERENCES `mydb`.`Inventario_Concesionario` (`idInventario_Concesionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `Sexo` VARCHAR(1) NOT NULL,
  `Ingreso` DOUBLE NULL,
  `Personacol` VARCHAR(45) NULL,
  `Clientes_idClientes` INT NOT NULL,
  CONSTRAINT `fk_Persona_Clientes1`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `mydb`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empresa` (
  `Tipo_Empresa` VARCHAR(45) NOT NULL,
  `Clientes_idClientes` INT NOT NULL,
  CONSTRAINT `fk_Empresa_Clientes1`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `mydb`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Color` (
  `idColor` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Modelo_idModelo` INT NOT NULL,
  PRIMARY KEY (`idColor`),
  INDEX `fk_Color_Modelo1_idx` (`Modelo_idModelo` ASC) VISIBLE,
  CONSTRAINT `fk_Color_Modelo1`
    FOREIGN KEY (`Modelo_idModelo`)
    REFERENCES `mydb`.`Modelo` (`idModelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
